
  spring:
    application:
      name: Inventory Control System
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect # Parametro exigido pelo RENDER
      hibernate:
        ddl-auto: update
        naming:
          physical-application: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
    datasource:
      url: jdbc:postgresql://dpg-d2tidcmuk2gs73ctvt00-a:5432/inventorycontroldb
      username: ${USER_DB}
      password: {PASSWORD_DB}
      driver-class-name: org.postgresql.Driver  # Parametro exigido pelo RENDER