spring:
  application:
    name: Inventory Control System
  jpa:
    hibernate:
      naming:
        physical-application: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_control?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: abc123.A
    driver-class-name: com.mysql.cj.jdbc.Driver